#!/usr/bin/python3
import tw


with tw.RecordDB() as db:
    with db.query as c:
        # gores
        c.execute("CREATE TABLE IF NOT EXISTS gores_race (Map VARCHAR(128) BINARY NOT NULL, Name VARCHAR(16) BINARY NOT NULL, Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , Time FLOAT DEFAULT 0, Server CHAR(4), cp1 FLOAT DEFAULT 0, cp2 FLOAT DEFAULT 0, cp3 FLOAT DEFAULT 0, cp4 FLOAT DEFAULT 0, cp5 FLOAT DEFAULT 0, cp6 FLOAT DEFAULT 0, cp7 FLOAT DEFAULT 0, cp8 FLOAT DEFAULT 0, cp9 FLOAT DEFAULT 0, cp10 FLOAT DEFAULT 0, cp11 FLOAT DEFAULT 0, cp12 FLOAT DEFAULT 0, cp13 FLOAT DEFAULT 0, cp14 FLOAT DEFAULT 0, cp15 FLOAT DEFAULT 0, cp16 FLOAT DEFAULT 0, cp17 FLOAT DEFAULT 0, cp18 FLOAT DEFAULT 0, cp19 FLOAT DEFAULT 0, cp20 FLOAT DEFAULT 0, cp21 FLOAT DEFAULT 0, cp22 FLOAT DEFAULT 0, cp23 FLOAT DEFAULT 0, cp24 FLOAT DEFAULT 0, cp25 FLOAT DEFAULT 0, GameID VARCHAR(64), KEY (Map, Name), KEY (Name)) CHARACTER SET utf8mb4")
        c.execute("CREATE TABLE IF NOT EXISTS gores_teamrace (Map VARCHAR(128) BINARY NOT NULL, Name VARCHAR(16) BINARY NOT NULL, Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, Time FLOAT DEFAULT 0, ID VARBINARY(16) NOT NULL, GameID VARCHAR(64), KEY Map (Map)) CHARACTER SET utf8mb4")
        # race, native
        c.execute("CREATE TABLE IF NOT EXISTS race_race (Map VARCHAR(128) BINARY NOT NULL, Name VARCHAR(16) BINARY NOT NULL, Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , Time FLOAT DEFAULT 0, Server CHAR(4), cp1 FLOAT DEFAULT 0, cp2 FLOAT DEFAULT 0, cp3 FLOAT DEFAULT 0, cp4 FLOAT DEFAULT 0, cp5 FLOAT DEFAULT 0, cp6 FLOAT DEFAULT 0, cp7 FLOAT DEFAULT 0, cp8 FLOAT DEFAULT 0, cp9 FLOAT DEFAULT 0, cp10 FLOAT DEFAULT 0, cp11 FLOAT DEFAULT 0, cp12 FLOAT DEFAULT 0, cp13 FLOAT DEFAULT 0, cp14 FLOAT DEFAULT 0, cp15 FLOAT DEFAULT 0, cp16 FLOAT DEFAULT 0, cp17 FLOAT DEFAULT 0, cp18 FLOAT DEFAULT 0, cp19 FLOAT DEFAULT 0, cp20 FLOAT DEFAULT 0, cp21 FLOAT DEFAULT 0, cp22 FLOAT DEFAULT 0, cp23 FLOAT DEFAULT 0, cp24 FLOAT DEFAULT 0, cp25 FLOAT DEFAULT 0, GameID VARCHAR(64), KEY (Map, Name), KEY (Name)) CHARACTER SET utf8mb4")
        c.execute("CREATE TABLE IF NOT EXISTS race_maps (Map VARCHAR(128) BINARY NOT NULL, Server VARCHAR(32) BINARY NOT NULL, Mapper VARCHAR(128) BINARY NOT NULL, Points INT DEFAULT 0, Stars INT DEFAULT 0, Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY Map (Map)) CHARACTER SET utf8mb4")
        c.execute("CREATE TABLE IF NOT EXISTS race_points (Name VARCHAR(16) BINARY NOT NULL, Points INT DEFAULT 0, UNIQUE KEY Name (Name)) CHARACTER SET utf8mb4")
        # race, unique specific
        c.execute("CREATE TABLE IF NOT EXISTS race_recordqueue (Id INT UNSIGNED NOT NULL AUTO_INCREMENT, Map VARCHAR(128) BINARY NOT NULL, Name VARCHAR(16) BINARY NOT NULL, Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, Time FLOAT DEFAULT 0, PRIMARY KEY(Id)) CHARACTER SET utf8mb4")
        c.execute("CREATE TABLE IF NOT EXISTS race_lastrecords (Id INT UNSIGNED NOT NULL AUTO_INCREMENT, Map VARCHAR(128) BINARY NOT NULL, Name VARCHAR(16) BINARY NOT NULL, Timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, Time FLOAT DEFAULT 0, PRIMARY KEY(Id)) CHARACTER SET utf8mb4")
        c.execute("CREATE TABLE IF NOT EXISTS race_catpoints (Server VARCHAR(32) BINARY NOT NULL, Name VARCHAR(16) BINARY NOT NULL, Points INT DEFAULT 0, UNIQUE KEY (Server, Name)) CHARACTER SET utf8mb4")
        c.execute("CREATE TABLE IF NOT EXISTS race_ranks (Map VARCHAR(128) BINARY NOT NULL, Name VARCHAR(16) BINARY NOT NULL, Rank INT, UNIQUE KEY (Map, Name)) CHARACTER SET utf8mb4")
